apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-webapp-verkoop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JipEmmerich/nginx-argo-app.git
    targetRevision: HEAD
    path: Verkoop
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-verkoop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
